CREATE TABLE IF NOT EXISTS PLACE_AGPZ
(
    ID    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLACE VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS WORKTASK_AGPZ
(
    ID       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK     VARCHAR(35) NOT NULL UNIQUE,
    PLACE VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS EMPLOYEE_AGPZ
(
    ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR(30) NOT NULL,
    POST        VARCHAR(30) NOT NULL,
    EXPERIENCE  FLOAT       NOT NULL,
    ID_WORKTASK INTEGER REFERENCES WORKTASK_AGPZ (ID)
);

